name: 'The Ghost of Jefferson'
author: ''
description: 'The Ghost of Jefferson - We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.'
keywords: 'jefferson, ghost, jefferson county, west virginia'
rss: 'Ghost of Jefferson'
analytics: 'UA-132973672-1'
social:
  email: 'editor@ghostofjefferson.com'
  facebook: 'https://facebook.com/GhostOfJefferson'
  twitter: 'https://twitter.com/ghstofjefferson'
  gab: ''
  mewe: ''
  fb_likes: 72
  tw_followers: 2

include:
  - _authors
  - _pages
  - _redirects

pagination:
  enabled: true
  per_page: 6
  permalink: '/page-:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

#excerpt_separator: <!--more-->
collections:
  authors:
    output: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

jekyll-archives:
  enabled: all
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    category: archive-tag
    tag: archive-tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor



