backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "assets/images"

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        searchFields: "name"
        valueField: "handle"
        displayFields: ["name"]
      - label: "Categories"
        name: "categories"
        widget: "select"
        options: ["News", "Opinion"]
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Image"
        name: "image"
        widget: "file"
        required: false
        media_library:
          config:
            multiple: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mm:ss"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "page"
    label: "Page"
    folder: "_pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Title"
        name: "title"
        widget: "string"
        tagname: "h1"
      - label: "Permalink"
        name: "permalink"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
  - name: "author"
    label: "Author"
    folder: "_authors"
    sort: "name:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Website"
        name: "url"
        widget: "string"
        required: false
      - label: "Email"
        name: "email"
        widget: "string"
        required: false
      - label: "Twitter"
        name: "twitter"
        widget: "string"
        required: false
      - label: "Facebook"
        name: "facebook"
        widget: "string"
        required: false
      - label: "Gab"
        name: "gab"
        widget: "string"
        required: false
      - label: "Mewe"
        name: "mewe"
        widget: "string"
        required: false
      - label: "Birthday"
        name: "date"
        widget: "date"
        format: "YYYY-MM-DD"
        required: false
      - label: "Bio"
        name: "bio"
        widget: "markdown"
        required: false
